---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: italians-maesi
  labels:
    app: italians-maesi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: italians-maesi
  template:
    metadata:
      labels:
        app: italians-maesi
    spec:
      containers:
      - name: italians-maesi
        image: maesi/ch-open-18:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /italians/resources/food
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: italians-maesi
spec:
  selector:
    app: italians-maesi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31081
  type: NodePort
